# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyID', models.CharField(max_length=200)),
                ('property_Address', models.CharField(max_length=200)),
                ('listed_date', models.DateTimeField(blank=True, null=True)),
                ('property_status', models.CharField(max_length=200)),
                ('listed_owner', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
