# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='House',
        ),
    ]
