# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0003_auto_20170523_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='listed_owner',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='created_date',
            new_name='CreateDate',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='propertyID',
            new_name='ListedAgent',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_Address',
            new_name='Postcode',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_status',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listed_date',
        ),
        migrations.AddField(
            model_name='property',
            name='ListedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='Property',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='SoldDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='SoldPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='SuburbName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
