# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0004_auto_20170526_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ID',
            new_name='PropertyID',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Property',
        ),
    ]
