# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0005_auto_20170526_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ModifiedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='Address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='ListedAgent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='Postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='SoldDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SoldPrice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
