# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0007_auto_20170527_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='CreateDate',
            new_name='createdate',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ListedAgent',
            new_name='listedagent',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ListedDate',
            new_name='listeddate',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ModifiedDate',
            new_name='midifydate',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='PropertyID',
            new_name='propertyid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='SoldDate',
            new_name='solddate',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='SoldPrice',
            new_name='soldprice',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='SuburbName',
            new_name='suburbname',
        ),
    ]
