# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0008_auto_20170624_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='midifydate',
            new_name='modifydate',
        ),
    ]
