# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0012_auto_20170625_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
